#!/bin/sh

if [ "$#" -lt "2" ]
then
	echo "USAGE: $0 <path to ingerc> <source code> [flags]..."
	echo
	echo "YOU PROBABLY WANT TO PASS AT LEAST -O"
	exit 1
fi

ingerc="$1"
program="$2"
shift 2

exec "$ingerc" "$@" -Clink-arg=-L. -Clink-arg=-Wl,-R\\\$ORIGIN -Clink-arg=-urealign -Clink-arg=realign.s -Clink-arg=-lunwind "$program" 
